apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: myapp
    rel: dev
spec:
  containers:
  - name: my-app
    image: my-image:1.0.1
    # test if pod is live  
    livenessProbe:
      httpGet:
        path: /health-cechk
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
      failureThreshold: 2
    # tests if pod is ready
    readinessProbe:
      httpGet:
        path: /api/version
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
